conf:
    name: Configuration app
    description: Welcome to ${conf.name}
    listValues: one,two,three
    values: "{conStr: 'This is connection string', user: 'username', pass: 'password'}"

db:
    connection: connection-string-test
    host: 172.0.0.1
    port: 3306
