conf:
    name: Configuration app
    description: Welcome to ${conf.name}
    listValues: one,two,three
    values: "{conStr: 'This is connection string', user: 'username', pass: 'password'}"

db:
    connection: connection-string
    host: 172.0.0.1
    port: 3306

management.endpoints.web.exposure.include: "*"

spring:
   # profiles:
      # active: default
   cloud:
      # inetutils:
         # useOnlySiteLocalInterfaces: true
      config:
         uri: http://localhost:8888
   application:
         name: spring-boot-config
